schemaVersion: 1
entityId: sequoia-getting-ready
sources:
  - id: seki-weather
    title: Weather
    publisher: National Park Service
    sourceType: primary-documentation
    url: https://www.nps.gov/seki/planyourvisit/weather.htm
    access: public
    retrievedAt: 2026-09-14T12:50:37-07:00
  - id: seki-bears
    title: Bears and food storage
    publisher: National Park Service
    sourceType: primary-documentation
    url: https://www.nps.gov/seki/planyourvisit/bears.htm
    access: public
    retrievedAt: 2026-09-14T12:50:37-07:00
  - id: nws-three-rivers
    title: Three Rivers point forecast
    publisher: National Weather Service
    sourceType: primary-documentation
    url: https://forecast.weather.gov/MapClick.php?lat=36.4389&lon=-118.904
    access: public
    retrievedAt: 2026-09-14T12:57:25-07:00
    fingerprint: 59a40409339f0bed40e897d37195dd75b50859695c18edb4d43e5bc5c015df25
  - id: nws-foothills-vc
    title: Foothills Visitor Center point forecast
    publisher: National Weather Service
    sourceType: primary-documentation
    url: https://forecast.weather.gov/MapClick.php?lat=36.4910724125&lon=-118.825590743
    access: public
    retrievedAt: 2026-09-14T12:57:25-07:00
    fingerprint: bf68760be841f14f26f3c373864a12ff02d455fb3f283d38097b7d0b757a206e
  - id: nws-lodgepole-vc
    title: Lodgepole Visitor Center point forecast
    publisher: National Weather Service
    sourceType: primary-documentation
    url: https://forecast.weather.gov/MapClick.php?lat=36.604134478373304&lon=-118.7319448096024
    access: public
    retrievedAt: 2026-09-14T12:57:25-07:00
    fingerprint: 59c545aab5586e27f65502ab297354714255d6e619fb97277da0291565d1d62f
  - id: nws-grant-grove-vc
    title: Grant Grove Visitor Center point forecast
    publisher: National Weather Service
    sourceType: primary-documentation
    url: https://forecast.weather.gov/MapClick.php?lat=36.7400152932&lon=-118.963419956
    access: public
    retrievedAt: 2026-09-14T12:57:25-07:00
    fingerprint: 754c7af21bfc50319980b2ffd64dac6081b46656159d0ff0fcccf19e8c39b65f
